# Generated by Django 5.2 on 2025-04-20 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='orderedmedicine',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='pharmacy.medicineorder'),
        ),
        migrations.AddField(
            model_name='orderedmedicine',
            name='replaced_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.orderedmedicine'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacyearning',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicineorder'),
        ),
        migrations.AddField(
            model_name='pharmacyearning',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacystaff',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacystaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
