# Generated by Django 5.2 on 2025-04-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_otp_base32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, default='UJP5MSURPSCFHM7UBBPGNX2EENDEIGFV', max_length=64),
        ),
    ]
