# Generated by Django 5.2 on 2025-04-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_otp_base32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, default='OHBRPQRK4PGS6YBEOZ2EGJSXK6KP4Z5T', max_length=64),
        ),
    ]
